export const USER_POSTS = [
  {
    id: 1,
    first_name: "Barbi",
    last_name: "Paterson",
    photo: "posts/34.jpg",
    date: "60 min ago",
    userID: 1,
    like: 135,
    comments: 731,
  },
  {
    id: 2,
    first_name: "Bunnie",
    last_name: "Bennallck",
    photo: "posts/35.jpg",
    description:
      "unde eaque repudiandae ex, reiciendis vitae ratione corrupti aperiam facere itaque eligendi cumque, animi similique laborum eius nostrum minus modi.",
    date: "1 min ago",
    userID: 2,
    like: 124,
    comments: 108,
  },
  {
    id: 3,
    first_name: "Calypso",
    last_name: "Nayshe",
    photo: "posts/36.jpg",
    description:
      "repellat aut iure in e eius ullam, nesciunt ab quasi animi incidunt debitis error. Eaque quidem expedita sit adipisci omnis aliquid cumque ipsum nam neque nobis, repellat maiores iam consectetur unde cumsdfg.",
    date: "14 min ago",
    userID: 3,
    like: 128,
    comments: 410,
  },
  {
    id: 4,
    first_name: "Constance",
    last_name: "Tipling",
    photo: "posts/37.jpg",
    date: "15 min ago",
    userID: 4,
    like: 38,
    comments: 492,
  },
  {
    id: 5,
    first_name: "Morey",
    last_name: "Boddymead",
    photo: "posts/38.jpg",
    description:
      " in nisi, quialiquid cumque ipsum nam nequea dolorem e eius ullam, nesciunt ab quasi animi incidunt debitis error. Eaque quidem expedita sit us ratione ad veritatis autem repellendus  rem, aperiam consectetur unde cumsdfg.",
    date: "16 min ago",
    userID: 5,
    like: 29,
    comments: 11,
  },
  {
    id: 6,
    first_name: "Ruddie",
    last_name: "Ughi",
    photo: "posts/39.jpg",
    description:
      " b quasi animi incidunt debitis error. Eaque quidem expedita sit adipisci omnis aliquid cumque ipsum nam neque nobis, repellat maiores dolque repellat aut iure in nisi, quia dolorem rem, aperiam consectetur unde cumsdfg.",
    date: "32 min ago",
    userID: 6,
    like: 114,
    comments: 344,
  },
  {
    id: 7,
    first_name: "Bern",
    last_name: "Pinnington",
    photo: "posts/40.jpg",
    description:
      "cidunt debitis error. Eaque quidem expedita sit adipisci omnis aliquid cumque ipsum nam neque nobis, repellat maiores dolorem consequunturepellendus  in nisi, quia dolorem rem, aperiam consectetur unde cumsdfg.",
    date: "57 min ago",
    userID: 7,
    like: 114,
    comments: 151,
  },
  {
    id: 8,
    first_name: "Berny",
    last_name: "Macieja",
    photo: "posts/41.jpg",
    date: "24 min ago",
    userID: 8,
    like: 144,
    comments: 532,
  },
  {
    id: 9,
    first_name: "Elise",
    last_name: "Pothecary",
    photo: "posts/42.jpg",
    description:
      " rem, aperiam consectetur e eius ullam, nesciunt ab quasi animi incidunt debitis error. Eaque quidem expedita sit adipisci omnis aliqu",
    date: "1 min ago",
    userID: 9,
    like: 144,
    comments: 884,
  },
  {
    id: 10,
    first_name: "Ashlee",
    last_name: "Skerm",
    photo: "posts/43.jpg",
    description:
      "repellat aut iure in nisi, quia dolorem rem, aperiam consectetur unde cumsdfg.",
    date: "25 min ago",
    userID: 10,
    like: 103,
    comments: 762,
  },
  {
    id: 11,
    first_name: "Scarface",
    last_name: "Quiney",
    photo: "posts/44.jpg",
    description:
      " iure in nisi, quia dolorem rem, aperiam consectetur unde cumsdfg.",
    date: "8 min ago",
    userID: 11,
    like: 12,
    comments: 598,
  },
  {
    id: 12,
    first_name: "Kassi",
    last_name: "Goodburn",
    description:
      "expedita sit adipisci omnis aliquid cumque ipsum nam neque nobis, repellat maiores dolorem consequuntur corrupti commodi natus ratione ad veritatis autem repellendus , quia dolorem rem, aperiam consectetur unde cumsdfg.",
    photo: "posts/45.jpg",
    date: "8 min ago",
    userID: 12,
    like: 69,
    comments: 204,
  },
  {
    id: 13,
    first_name: "Fania",
    last_name: "Beves",
    photo: "posts/46.jpg",
    description:
      "Eaque quidem expedita sit adipisci omnis aliquid cumque ipsum  maiores dolorem consequuntur corrupti commodi natus ratione ad veritatis autem repellendus  repellat aut iure in nisi, quia dolorem rem, aperiam consectetur unde cumsdfg.",
    date: "10 min ago",
    userID: 13,
    like: 70,
    comments: 331,
  },
  {
    id: 14,
    first_name: "Sher",
    last_name: "Alenikov",
    photo: "posts/47.jpg",
    description:
      "nam neque nobis, repellat repellat aut iure in nisi, quia dolorem rem, aperiam consectetur unde cumsdfg.",
    date: "60 min ago",
    userID: 14,
    like: 46,
    comments: 930,
  },
  {
    id: 15,
    first_name: "Lenard",
    last_name: "Garfield",
    photo: "posts/48.jpg",
    description:
      "nam neque nobis, repellat iure in nisi, quia dolorem rem, aperiam consectetur unde cumsdfg.",
    date: "52 min ago",
    userID: 15,
    like: 10,
    comments: 133,
  },
  {
    id: 16,
    first_name: "Marysa",
    last_name: "Dudding",
    photo: "posts/49.jpg",
    description:
      "omnis aliquid cumque ipsum nam neque nobis, repell repellat aut iure in nisi, quia dolorem rem, aperiam consectetur unde cumsdfg.",
    date: "12 min ago",
    userID: 16,
    like: 93,
    comments: 88,
  },
  {
    id: 17,
    first_name: "Pyotr",
    last_name: "Stivens",
    photo: "posts/50.jpg",
    description:
      "repellat aut iure in nisi, quia dolorem rem, aperiam consectetur unde cumsdfg.",
    date: "18 min ago",
    userID: 17,
    like: 82,
    comments: 222,
  },
  {
    id: 18,
    first_name: "My",
    last_name: "Meuse",
    photo: "posts/51.jpg",
    description:
      "repellat aut iure in nisi, quia dolorem rem, aperiam consectetur unde cumsdfg.",
    date: "32 min ago",
    userID: 18,
    like: 138,
    comments: 464,
  },
  {
    id: 19,
    first_name: "Caritta",
    last_name: "Osmint",
    photo: "posts/52.jpg",
    description:
      "repellat aut iure in nisi, quia dolorem rem, aperiam consectetur unde cumsdfg.",
    date: "9 min ago",
    userID: 19,
    like: 17,
    comments: 281,
  },
  {
    id: 20,
    first_name: "Nevsa",
    last_name: "Lynde",
    photo: "posts/53.jpg",
    description:
      "repellat aut iure in nisi, quia dolorem rem, aperiam consectetur unde cumsdfg.",
    date: "30 min ago",
    userID: 20,
    like: 69,
    comments: 19,
  },
  {
    id: 21,
    first_name: "Reinhold",
    last_name: "MacSkeaghan",
    photo: "posts/54.jpg",
    description:
      "repellat aut iure in nisi, quia dolorem rem, aperiam consectetur unde cumsdfg.",
    date: "25 min ago",
    userID: 21,
    like: 136,
    comments: 137,
  },
  {
    id: 22,
    first_name: "Geri",
    last_name: "Prestney",
    photo: "posts/55.jpg",
    description:
      "repellat aut iure in nisi, quia dolorem rem, aperiam consectetur unde cumsdfg.",
    date: "13 min ago",
    userID: 22,
    like: 8,
    comments: 121,
  },
  {
    id: 23,
    first_name: "Lynn",
    last_name: "Larrat",
    photo: "posts/56.jpg",
    description:
      "repellat aut iure in nisi, quia dolorem rem, aperiam consectetur unde cumsdfg.",
    date: "56 min ago",
    userID: 23,
    like: 143,
    comments: 589,
  },
  {
    id: 24,
    first_name: "Eolande",
    last_name: "Tollett",
    photo: "posts/57.jpg",
    description:
      "repellat aut iure in nisi, quia dolorem rem, aperiam consectetur unde cumsdfg.",
    date: "12 min ago",
    userID: 24,
    like: 45,
    comments: 169,
  },
  {
    id: 25,
    first_name: "Rosabel",
    last_name: "Smallpeace",
    photo: "posts/58.jpg",
    description:
      "repellat aut iure in nisi, quia dolorem rem, aperiam consectetur unde cumsdfg.",
    date: "59 min ago",
    userID: 25,
    like: 103,
    comments: 631,
  },
  {
    id: 26,
    first_name: "Valina",
    last_name: "Eardley",
    photo: "posts/59.jpg",
    description:
      "repellat aut iure in nisi, quia dolorem rem, aperiam consectetur unde cumsdfg.",
    date: "37 min ago",
    userID: 26,
    like: 28,
    comments: 670,
  },
  {
    id: 27,
    first_name: "Margret",
    last_name: "Licciardo",
    photo: "posts/60.jpg",
    description:
      "repellat aut iure in nisi, quia dolorem rem, aperiam consectetur unde cumsdfg.",
    date: "41 min ago",
    userID: 27,
    like: 138,
    comments: 290,
  },
  {
    id: 28,
    first_name: "Rori",
    last_name: "Beckinsall",
    photo: "posts/61.jpg",
    description:
      "repellat aut iure in nisi, quia dolorem rem, aperiam consectetur unde cumsdfg.",
    date: "37 min ago",
    userID: 28,
    like: 64,
    comments: 830,
  },
  {
    id: 29,
    first_name: "Katrinka",
    last_name: "Tuffin",
    photo: "posts/62.jpg",
    description:
      "repellat aut iure in nisi, quia dolorem rem, aperiam consectetur unde cumsdfg.",
    date: "26 min ago",
    userID: 29,
    like: 71,
    comments: 736,
  },
  {
    id: 30,
    first_name: "Peggy",
    last_name: "Tegeller",
    photo: "posts/63.jpg",
    description:
      "repellat aut iure in nisi, quia dolorem rem, aperiam consectetur unde cumsdfg.",
    date: "27 min ago",
    userID: 30,
    like: 180,
    comments: 362,
  },
  {
    id: 31,
    first_name: "Enoch",
    last_name: "Biddell",
    photo: "posts/64.jpg",
    description:
      "repellat aut iure in nisi, quia dolorem rem, aperiam consectetur unde cumsdfg.",
    date: "36 min ago",
    userID: 31,
    like: 40,
    comments: 366,
  },
  {
    id: 32,
    first_name: "Ellette",
    last_name: "Broxholme",
    photo: "posts/65.jpg",
    description:
      "repellat aut iure in nisi, quia dolorem rem, aperiam consectetur unde cumsdfg.",
    date: "34 min ago",
    userID: 32,
    like: 160,
    comments: 960,
  },
  {
    id: 33,
    first_name: "Bette",
    last_name: "Skep",
    photo: "posts/67.jpg",
    description:
      "repellat aut iure in nisi, quia dolorem rem, aperiam consectetur unde cumsdfg.",
    date: "56 min ago",
    userID: 33,
    like: 128,
    comments: 578,
  },
  {
    id: 34,
    first_name: "Keelia",
    last_name: "Leborgne",
    photo: "posts/68.jpg",
    description:
      "repellat aut iure in nisi, quia dolorem rem, aperiam consectetur unde cumsdfg.",
    date: "55 min ago",
    userID: 34,
    like: 162,
    comments: 253,
  },
  {
    id: 35,
    first_name: "Elvis",
    last_name: "Lester",
    photo: "posts/69.jpg",
    description:
      "repellat aut iure in nisi, quia dolorem rem, aperiam consectetur unde cumsdfg.",
    date: "46 min ago",
    userID: 35,
    like: 30,
    comments: 328,
  },
  {
    id: 36,
    first_name: "Ellerey",
    last_name: "Bordessa",
    photo: "posts/70.jpg",
    description:
      "repellat aut iure in nisi, quia dolorem rem, aperiam consectetur unde cumsdfg.",
    date: "46 min ago",
    userID: 36,
    like: 69,
    comments: 87,
  },
  {
    id: 37,
    first_name: "Burty",
    last_name: "Coggeshall",
    photo: "posts/71.jpg",
    description:
      "repellat aut iure in nisi, quia dolorem rem, aperiam consectetur unde cumsdfg.",
    date: "52 min ago",
    userID: 37,
    like: 148,
    comments: 55,
  },
  {
    id: 38,
    first_name: "Jereme",
    last_name: "Bigglestone",
    photo: "posts/72.jpg",
    description:
      "repellat aut iure in nisi, quia dolorem rem, aperiam consectetur unde cumsdfg.",
    date: "48 min ago",
    userID: 38,
    like: 169,
    comments: 515,
  },
  {
    id: 39,
    first_name: "Dion",
    last_name: "Johnke",
    photo: "posts/73.jpg",
    description:
      "repellat aut iure in nisi, quia dolorem rem, aperiam consectetur unde cumsdfg.",
    date: "55 min ago",
    userID: 39,
    like: 114,
    comments: 757,
  },
  {
    id: 40,
    first_name: "Allianora",
    last_name: "Marti",
    photo: "posts/74.jpg",
    description:
      "repellat aut iure in nisi, quia dolorem rem, aperiam consectetur unde cumsdfg.",
    date: "28 min ago",
    userID: 40,
    like: 58,
    comments: 873,
  },
  {
    id: 41,
    first_name: "Burl",
    last_name: "Wratten",
    photo: "posts/75.jpg",
    description:
      "repellat aut iure in nisi, quia dolorem rem, aperiam consectetur unde cumsdfg.",
    date: "36 min ago",
    userID: 41,
    like: 192,
    comments: 691,
  },
  {
    id: 42,
    first_name: "Etienne",
    last_name: "Atmore",
    photo: "posts/76.jpg",
    description:
      "repellat aut iure in nisi, quia dolorem rem, aperiam consectetur unde cumsdfg.",
    date: "23 min ago",
    userID: 42,
    like: 61,
    comments: 677,
  },
  {
    id: 43,
    first_name: "Indira",
    last_name: "Millhill",
    photo: "posts/77.jpg",
    description:
      "repellat aut iure in nisi, quia dolorem rem, aperiam consectetur unde cumsdfg.",
    date: "49 min ago",
    userID: 43,
    like: 24,
    comments: 611,
  },
  {
    id: 44,
    first_name: "Marshal",
    last_name: "Dietzler",
    photo: "posts/78.jpg",
    description:
      "repellat aut iure in nisi, quia dolorem rem, aperiam consectetur unde cumsdfg.",
    date: "37 min ago",
    userID: 44,
    like: 93,
    comments: 364,
  },
  {
    id: 45,
    first_name: "Loralyn",
    last_name: "Keetley",
    photo: "posts/79.jpg",
    description:
      "repellat aut iure in nisi, quia dolorem rem, aperiam consectetur unde cumsdfg.",
    date: "25 min ago",
    userID: 45,
    like: 93,
    comments: 101,
  },
  {
    id: 46,
    first_name: "Melessa",
    last_name: "Boch",
    photo: "posts/80.jpg",
    description:
      "repellat aut iure in nisi, quia dolorem rem, aperiam consectetur unde cumsdfg.",
    date: "38 min ago",
    userID: 46,
    like: 164,
    comments: 857,
  },
  {
    id: 47,
    first_name: "Keelia",
    last_name: "Steane",
    photo: "posts/81.jpg",
    description:
      "repellat aut iure in nisi, quia dolorem rem, aperiam consectetur unde cumsdfg.",
    date: "54 min ago",
    userID: 47,
    like: 187,
    comments: 784,
  },
  {
    id: 48,
    first_name: "Dorita",
    last_name: "Bolingbroke",
    photo: "posts/82.jpg",
    description:
      "repellat aut iure in nisi, quia dolorem rem, aperiam consectetur unde cumsdfg.",
    date: "59 min ago",
    userID: 48,
    like: 186,
    comments: 933,
  },
  {
    id: 49,
    first_name: "Noel",
    last_name: "Scowcroft",
    photo: "posts/83.jpg",
    description:
      "repellat aut iure in nisi, quia dolorem rem, aperiam consectetur unde cumsdfg.",
    date: "7 min ago",
    userID: 49,
    like: 35,
    comments: 753,
  },
  {
    id: 50,
    first_name: "Giavani",
    last_name: "McCullough",
    photo: "posts/84.jpg",
    description:
      "repellat aut iure in nisi, quia dolorem rem, aperiam consectetur unde cumsdfg.",
    date: "21 min ago",
    userID: 50,
    like: 118,
    comments: 786,
  },
  {
    id: 51,
    first_name: "Deedee",
    last_name: "Marking",
    photo: "posts/85.jpg",
    description:
      "repellat aut iure in nisi, quia dolorem rem, aperiam consectetur unde cumsdfg.",
    date: "30 min ago",
    userID: 51,
    like: 112,
    comments: 134,
  },
  {
    id: 52,
    first_name: "Buck",
    last_name: "Kigelman",
    photo: "posts/86.jpg",
    description:
      "repellat aut iure in nisi, quia dolorem rem, aperiam consectetur unde cumsdfg.",
    date: "39 min ago",
    userID: 52,
    like: 114,
    comments: 279,
  },
  {
    id: 53,
    first_name: "Dagmar",
    last_name: "Swannick",
    photo: "posts/87.jpg",
    description:
      "repellat aut iure in nisi, quia dolorem rem, aperiam consectetur unde cumsdfg.",
    date: "29 min ago",
    userID: 53,
    like: 71,
    comments: 890,
  },
];
